### ISSUE TITLE
frequent fetch timed out and waiting for completion URL issues after upgrading pagespeed 1.9.32

### ISSUE THREAD

**Issue by Siva-Moorthy** [apache/incubator-pagespeed-mod#1072]
Hi, 

I've recently upgraded pagespeed to 1.9.32 version . Previously we used to get previous fetch time out issue once in a week and done restart apache as fix. To reduce this issue, we decreases image fetch rate to minimum (2) and again faced the same issue. 

But after upgrading , we r getting new errors as below while getting fetch timed out errors. 

[mod_pagespeed 1.9.32.3]  Waiting for completion of URL​ www.example.com 

Due to this, out webserver is going to hung state often than previous versions . 

Pls anyone contact me at the earliest to guide me to fix this. 

Thanks , Siva

**Comment by eldk** [comment]
Hello,

You should have a look here : https://github.com/pagespeed/mod_pagespeed/issues/1048

Thanks,

Eric

**Comment by jeffkaufman** [comment]
Sorry, we're still working on debugging #1048.

For now, the workaround is to turn off IPRO:

```
ModPagespeedInPlaceResourceOptimization off
```

**Comment by jeffkaufman** [comment]
@Siva-Moorthy are you still having this issue? We're preparing a release with a mitigation for the bug, but because we haven't been able to reproduce it here it would be really very helpful if you could install https://github.com/pagespeed/mod_pagespeed/releases/tag/1.9.32.5 which has the draft fix, and let us know it the problem recurs.
