### ISSUE TITLE
Invalid command 'ModPagespeedMemcachedServer', perhaps misspelled or defined by a module not included in the server configuration

### ISSUE THREAD

**Issue by webtoolbox** [apache/incubator-pagespeed-mod#1128]
I get this error when I run apache2ctl -t: Invalid command 'ModPagespeedMemcachedServer', perhaps misspelled or defined by a module not included in the server configuration

I have specified:
ModPagespeedMemcachedServer pagespeed.ip3lzw.cfg.use1.cache.amazonaws.com:11211

Is something else needed on the server to be able to use memcached?

We don't have any memcached software or modules installed on the server since it needs to communicate with AWS ElastiCache. However, that doesn't seem like the problem because it doesn't seem to even recognize the directive.

I am using the stable current release downloaded from here just now: https://dl-ssl.google.com/dl/linux/direct/mod-pagespeed-stable_current_amd64.deb

**Comment by jmarantz** [comment]
ModPagespeedMemcachedServer_s_

you forgot the last 's'.  It's plural because you can use more than one
memcached server to shard your cache lookups.

However, when you try this, please take a look at your apache logs and the
mod_pagespeed statistics pages to make sure you aren't getting timeouts.
By default the system is tuned for a local memcached, and you may need to
tweak the timeouts.

Please see
https://developers.google.com/speed/pagespeed/module/system#memcached for
details.

-Josh
