### ISSUE TITLE
Problem with the aspect ratio of the images by resize_image

### ISSUE THREAD

**Issue by ghost** [apache/incubator-pagespeed-mod#1147]
Hi,

Issue:

The images on my website's sidebar are all with a wrong aspect ratio after resizing. The only fix for this is to disable rewrite_images but it is one of the best speed bumps, so I am looking how I can fix the aspect ratio.

Screenshots:

resize_image disabled: http://prntscr.com/8lcfdj
resize_image enabled: http://prntscr.com/8lcfux

System:

I am using mod_pagespeed which is running on Apache server trough the Nginx module.

OS: CentOS 6.4 (64 bit)
Nginx pagespeed: ngx_pagespeed-release-1.9.32.3-beta
Apache pagespeed: mod_pagespeed-1.7.30.5-0.x86_64
Other versions: https://supplementswatch.com/info.php

Rules:

pagespeed RewriteLevel CoreFilters;
pagespeed EnableFilters inline_google_font_css;
pagespeed EnableFilters remove_comments;
pagespeed EnableFilters extend_cache;
pagespeed DisableFilters insert_image_dimensions;

**Comment by ghost** [comment]
Anyone?

**Comment by jeffkaufman** [comment]
Looking at the html I see:

```
<img itemprop="image" class="widget_review_screenshot_img photo"
     src="..." alt="Bulking Stack" width="320" height="180">
```

The image itself is 680x300.

There's also css with:

```
media="all"
img, video, object {
    ...
    height: auto!important;
    ...
}
```

That `height` directive ends up in context at setting the image height to 66px, and then the browser maintains the 680x300 ratio of the source image and sets the width to 149.9px.

The problem is PageSpeed doesn't understand your whole css setup, and instead just goes with the `width="320" height="180"` in the html.  But 320x180 is 16:9 while 680x300 is closer to 16:7, so this gets the aspect ratio wrong.

To fix this, you could either remove the width and height tags from the image, which the browser is just ignoring, you could turn off the `resize_images` filter, or you could turn on the `resize_rendered_image_dimensions` filter that uses beaconing to handle css problems like yours.

More doc: https://developers.google.com/speed/pagespeed/module/filter-image-optimize#resize_images

**Comment by ghost** [comment]
Thanks
