### ISSUE TITLE
Mobile optimized images - what about pixel density?

### ISSUE THREAD

**Issue by GuillaumeRossolini** [apache/incubator-pagespeed-mod#1206]
Hi,
I haven't read any mention of how pixel density is handled, particularly with mobile optimizations. For instance Apple's Retina or Google's Pixel screens.
cf. JpegRecompressionQualityForSmallScreens
Could you please expand?
Thanks,

**Comment by jmaessen** [comment]
mod_pagespeed uses the SmallScreens settings for mobile device user agents.  If you are serving a high-pixel-count image to retina devices, this will recompress it using the small screen recompression quality.  This is almost certainly what you want, since the higher pixel count images are otherwise dramatically larger than the non-retina equivalents, and it's generally impossible for users to notice the image quality difference without zooming in quite a bit.

**Comment by GuillaumeRossolini** [comment]
Ok then I still need a high-res variant.
I can't tell mod_pagespeed to recompress images for mobile except high-res screens, right?

**Comment by jmarantz** [comment]
We have a feature to be released very soon which will deliver higher res
images to retina screens via srcset.  Please stay tuned!  We are just
putting the wraps on the release that supports this new feature.

**Comment by GuillaumeRossolini** [comment]
That would be great! Thanks!
