### ISSUE TITLE
Slow read operation on file  -- configure SlowFileLatencyUs to change threshold\n

### ISSUE THREAD

**Issue by Kripan** [apache/incubator-pagespeed-mod#1247]
HI all,
i facing strange issue from last 2 day i am getting this messages in my logs every second which was working fine before a week.

[Tue Jan 19 15:33:23 2016] [error] [mod_pagespeed 1.9.32.10-7443 @30421] Slow read operation on file /pspeed_cache/mbhaskar/v2/bhaskar.com/http,3A/,2Fm.bhaskar.com/news-whf/JM-JKR-CN-this-is-the-chanakya-s-30-thought-5226081-PHO.html,3Fseq=24,: 110.455ms; configure SlowFileLatencyUs to change threshold\n

Below is my conf & filters
Version: 14: on

Filters
cw  Collapse Whitespace
dj  Defer Javascript
ea  Elide Attributes
fc  Fallback Rewrite Css 
hw  Flushes html
idp Insert DNS Prefetch
ll  Lazyload Images
cj  Move Css Above Scripts
jm  Rewrite External Javascript
jj  Rewrite Inline Javascript

Options
  CriticalImagesBeaconEnabled (cibe)  False
  EnableCachePurge (euci)             True
  EnableRewriting (e)                 1
  FileCacheCleanIntervalMs (afcci)    3600000
  FileCacheInodeLimit (afcl)          500000
  FileCachePath (afcp)                /pspeed_cache/mbhaskar/
  FileCacheSizeKb (afc)               209715200
  LogDir (ald)                        /var/log/pagespeed
  LRUCacheByteLimit (alcb)            16384
  LRUCacheKbPerProcess (alcp)         1024
  RateLimitBackgroundFetches (rlbf)   False
  RewriteLevel (l)                    Pass Through
  SslCertDirectory (assld)            /etc/pki/tls/certs
  SslCertFile (asslf)                 /etc/pki/tls/cert.pem

**Comment by Kripan** [comment]
Please help me as its increasing my owait

**Comment by jmarantz** [comment]
What kind of disk is /pspeed_cache ?  Is it a network disk?

**Comment by Zwilla** [comment]
"110.455ms; configure SlowFileLatencyUs to "

ModPagespeedInPlaceResourceOptimization on
ModPagespeedInPlaceRewriteDeadlineMs 111

thats all, I think. Can you confirm this?

**Comment by RobertoDonPedro** [comment]
Hi, I experience the same issues: [pagespeed:error]: configure SlowFileLatencyUs to change threshold
Adding this had no positve effect:
ModPagespeedInPlaceResourceOptimization on
ModPagespeedInPlaceRewriteDeadlineMs 100

It seems that this error comes always after this one:
[access_compat:error]  client denied by server configuration: /xmlrpc
.php
I had and still have to block xmlrpc.php because of massive brute force attacks against this file.
However, my system is still slowing down amazingly. 
Any ideas how to fix this? Thx!

**Comment by oschaaf** [comment]
@RobertoDonPedro at what frequency do you get these messages? (If they are infrequent, there might not be an issue, it's just mod_pagespeed reporting that your disk is slow to respond). 

Adding this to your configuration may help save some mod_pagespeed induced disk i/o for the url that is being brute-forced:
```
ModPageSpeedDisallow /xmlrpc*
```

Taking a look at the console and raw statistics in the admin pages may give some insights into mod_pagespeed's health:
https://modpagespeed.com/doc/admin

**Comment by RobertoDonPedro** [comment]
Hi Otto, thx for the quick response.
It appeared in minutes...
This line indeed seems to eliminate the [pagespeed:error] message, but it is not the cause...:-(. 
The System still is lousy slow...-(

**Comment by oschaaf** [comment]
The logged lines about `SlowFileLatencyUs` is a symptom of the disk being slow to respond. 

The console & statistics pages may be helpful in that they show hit/miss/eviction rates of the caches. Maybe bumping the in-memory caches (lru, shared memory) could do with some more space, and that could take some load off the filesystem: https://modpagespeed.com/doc/system#lru_cache

If that does not help, a more drastic remedy would be to replace mod_pagespeed's stock filesystem-cache with memcached: https://modpagespeed.com/doc/system#memcached

Doing so would reduce mod_pagespeed's disk i/o to almost none (except for large files, and periodic scanning and snapshotting on behalf of some of mod_pagespeed's subsystems).

**Comment by RobertoDonPedro** [comment]
Just checked the error log again. The pagespeed errors are still there, now for other files than xmlrpc.php:
68.655ms; configure SlowFileLatencyUs to change threshold\n
So this line seems to have no positive impact:
ModPagespeedInPlaceRewriteDeadlineMs 100

**Comment by oschaaf** [comment]
`ModPagespeedInPlaceRewriteDeadlineMs 100` will not impact the speed of your disk, but it will impact how long mod_pagespeed will wait for optimizations to complete before sending out a response.

**Comment by RobertoDonPedro** [comment]
Yes, I got this one. But if the access time is just 
`68.655ms`, 
shouldn't this directive 
`ModPagespeedInPlaceRewriteDeadlineMs 100`
suppress  the message
`68.655ms; configure SlowFileLatencyUs to change threshold\n` ?

**Comment by oschaaf** [comment]
@RobertoDonPedro 
No, you can configure the threshold for logging with `ModPagespeedSlowFileLatencyUs` (in microseconds)

**Comment by RobertoDonPedro** [comment]
Oh thanks, quite obvious but I did not see this...
Regarding the performance itself, I run a Google Cloud Virtual Machine of type "1 vCPU, 0,6 GB".
The performance was very good until one week, the only thing I did was upgrading to the latest wordpress version, but I do not think, that there is a relation with this update and the poor performance I do have right now.
Is there something I can optimize with this just 0,6 GB mem micro instance?

**Comment by oschaaf** [comment]
@RobertoDonPedro 
Could you try if disabling the cache cleaner helps, by setting `ModPagespeedFileCacheCleanIntervalMs` to a very high value?:
(in 1.12.x you can set it to -1 to disable it: https://modpagespeed.com/doc/system#file_cache)

If that does not help: I'm not sure what headroom you have left in the 0,6GB of memory the server has. But as I understand it your website would benefit from reducing disk i/o.  So see my earlier comment on configuring the caches: https://github.com/pagespeed/mod_pagespeed/issues/1247#issuecomment-274499360
If your in-memory caches are too small, you are bound to have frequent cache lookups that will end up doing disk i/o.

If all else fails you could try to trade in features to reduce cache usage and lookups (and with that potential disk i/o): 
- maybe try disabling `InPlaceResourceOptimization` 
- maybe disable prioritize critical css, and lazyload images, any filters that rely on beaconing. 
I am not sure that doing that disabling these will make a noticeable difference, but I'd be curious to hear if it turns out it does.

**Comment by RobertoDonPedro** [comment]
`ModPagespeedFileCacheCleanIntervalMs -1`
ends up in 
`[mod_pagespeed 1.9.32.14-0 @30763] Next scheduled file cache clean time 1485257348825 is implausibly remote.  Cleaning now.`

`ModPagespeedFileCacheCleanIntervalMs 10000000`
makes it even 2 seconds slower 

Regarding  in-memory LRU Cache:
`ModPagespeedLRUCacheKbPerProcess     4096`
does not make any difference

Funny thing is that completely disabling ModPageSpeed with
`ModPagespeed off`
does not make any difference, too.

**Comment by oschaaf** [comment]
Well, if `ModPagespeed off` does not make a difference, then I'm not sure there is anything I can do to help you out here.

**Comment by ponchov** [comment]
I'm having the exact same issue:

2017/11/17 14:01:36 [error] 14643#0: [ngx_pagespeed 1.12.34.2-0] Slow ReadFile operation on file /var/ngx_pagespeed_cache/v3/www.mysite.com/http,3A/,2Fwww.mysite.com/photos/tns/tns_1631541.jpg,3F10242015073202,: 331.253ms; configure SlowFileLatencyUs to change threshold

When I turn off Pagespeed module it disappear, any suggestion? I've tried all the suggestions on this thread

**Comment by jonshkreli** [comment]
Hi @Kripan and @ponchov ! Did you find solutions for them?

I am expiring this issue suddenly since 2 days ago. Suddenly my WP is slow and wp-admin is very very slow.

Here is a sample of my error_log from apache2. I have blocked this ip 92.53.65.22, that's why it gets that message.
`[Sun Feb 17 10:14:22.415350 2019] [pagespeed:error] [pid 27392:tid 139963488024320] [mod_pagespeed 1.9.32.14-0 @27392] Slow read operation on file /opt/bitnami/apache2/var/cache/mod_pagespeed/rname/ic_YddRYU7ik1Q__FFD5Qku/http,3A/,2Fdsmtours.com/wp-content/uploads/2017/12/brezovice-1-640x463.jpg,40x,40ss_,: 77.296ms; configure SlowFileLatencyUs to change threshold\n
[Sun Feb 17 10:14:22.496691 2019] [authz_core:error] [pid 26456:tid 139963622307584] [client 92.53.65.22:41560] AH01630: client denied by server configuration: /opt/bitnami/apps/wordpress/htdocs/xmlrpc.php
`

One question to all: should **daemon** user own "/opt/bitnami/apache2/var"? And its subfolders as cache?

Please help!!!
May my server be hacked?
Also 2 days ago I noticed that daemon user owned some files in one wp website. It is very strange since I haven't touch it for a long time.
