### ISSUE TITLE
Add support for `Save-Data` request header

### ISSUE THREAD

**Issue by igrigorik** [apache/incubator-pagespeed-mod#1258]
https://httpwg.github.io/http-extensions/client-hints.html#the-save-data-hint

When the `Save-Data` header is present, PageSpeed should automatically adjust its filters and optimizations to reduce the amount of served bytes -- e.g. compress images with lower quality. Ideally, this should be an "on by default" behavior, but one that can be (re)configured by the site owner.

**Comment by huibaolin** [comment]
To support Save-Data, we'll add 2 new quality levels:
- WebpQualityForSaveData
- JpegQualityForSaveData

To enable this feature, and also make the optimized friendly to CDN/proxy, we'll add a new option:
- AllowVaryOn. 

AllowVaryOn will list the headers which the optimized images can vary on. Currently it will support these: Accept, User-Agent, and Save-Data. It can also be "Auto" by which PageSpeed will pick the proper list of header depends on whether the request has Via header or not.

**Comment by igrigorik** [comment]
@huibaolin great stuff, thanks! A couple of followup questions:
- What will the default quality values be for *SaveData settings?
- Will `AllowVaryOn` be on by default? If not, what stops us from turning it on by default?

**Comment by huibaolin** [comment]
WebpQualityForSaveData will be defaulted to 50, which is the quality used in Chrome Data Saver. JpegQualityForSaveData will be set to match WebP 50. I'll run some experiments to find out the exact value.

AllowVaryOn will be defaulted to "Auto". By "Auto" we'll try to use the most meaningful value for the user.
- If the request has a "Via" header, we assume that it was through a CDN/proxy, so we will allow varying on "Accept" and "Save-Data" headers.
- Otherwise, we assume that the request was from the user agent directly. We'll try all images formats supported by the UA, and will allow "User-Agent" and "Save-Data".

**Comment by jeffkaufman** [comment]
Fixed by 1fef4af, e686449, 5da54d8, 6c0be2e, b98bf9a, 79eb6fa, c0b22d1, and b92ddc1.  Squash-merged these to 408b027969aab3ef97bd86934ca2576cf0b95dc0 for the 1.11 release.
