### ISSUE TITLE
Serve resources from a consistent URL after installing mod_pagespeed 

### ISSUE THREAD

**Issue by ypmict** [apache/incubator-pagespeed-mod#1297]
Hi,
I using the gtmetrix.com for my website benchmark, before installing mod_pagespeed there is no such that error, but after that I got that error after running the benchmark tool... the error example is a as below :

**Serve resources from a consistent URL**

`The following resources have identical contents, but are served from different URLs. Serve these resources from a consistent URL to save 1 request(s) and 92.4KiB.

http://www.mydomain.com/images/template/slide/KUDoSwk.jpg
http://www.mydomain.com/images/template/slide/xKUDoSwk.jpg.pagespeed.ic.MRlqvTlFDh.jpg`

..and a lot of them, it listed out with the image file only I think

Thank you very much...

**Comment by oschaaf** [comment]
- Is this a transient error? Does it go away after a couple of browser refreshes?
- Could you post (or email me) the url of the website?

**Comment by ypmict** [comment]
Hi,
I already e-mail our website link... it looks like a permanent error.
Thank you very much for the feedback..

**Comment by oschaaf** [comment]
Thanks - I received the url of your website.
Your website has a slider implemented in javascript on the page which loads
images declared via "data-thumb" attributes on "li" tags.

The complaints about inconsistent urls are because mod_pagespeed does not
process these data-thumb attributes.
Adding the following to your pagespeed configuration should fix the
inconsistent urls that are reported:

ModPagespeedUrlValuedAttribute li data-thumb image

For more information, see
https://developers.google.com/speed/pagespeed/module/domains#url-valued-attributes

Otto

**Comment by ypmict** [comment]
I added the syntax to my pagespeed.conf..  It works now... thank you very much... :+1:

**Comment by ypmict** [comment]
Hi.. sorry, I just realize that when adding the syntax and turn on mod_pagespeed, my total website "Total Page Size" seems to doubled.. and page load time also increase a little bit anything wrong?
you can check the gtmetrix.com test screenshot for the comparison:

![mod_pagespeed-compare](https://cloud.githubusercontent.com/assets/8087038/15203067/9fcc87d4-1832-11e6-90e9-7815feae1b7f.png)

Thanks

**Comment by oschaaf** [comment]
I think there's something odd happening here.. the (anonymized) essence of what I'm seeing:

``` html
<li  data-thumb="http://www.domain.com/path/to/image-AA-AA.jpg.pagespeed.ce.j_M6m_1qwr.jpg">
<img src=""http://www.domain.com/path/to/image-AA.jpg.pagespeed.ic.dPKpjl3OxI.webp" pagespeed_url_hash="349959412" onload="pagespeed.CriticalImages.checkImageForCriticality(this);">
<!--Image does not appear to need resizing.-->
<!--The image was not inlined because it has too many bytes.-->
```

So two different versions of the same image end up in the html, which explains the increased total page size.

Could you open a new issue for this, and email me your (pagespeed) configuration?

**Comment by ypmict** [comment]
Hi,
ok I just e-mailed my pagespeed config... actually the way I am using the pagespeed is by using 2 separate config which is one for default config and the other one is for dedicated config for the only website that modpage_speed is enabled that is by using the 'include' syntax in Apache config for certain virtual host.
Thank you very much for the feedback, really appreciated it.

**Comment by mejbabiplob** [comment]
Hello,
I am using CND. here is the problem.

The following resources have identical contents, but are served from different URLs. Serve these resources from a consistent URL to save 1 request(s) and 26.9KiB.

https://delmsky2m3lys.cloudfront.net/wp-content/uploads/2015/11/caddytek-ez-fold-3-wheel-golf-push-cart.png
https://www.bestgolfcartsreviews.com/wp-content/uploads/2015/11/caddytek-ez-fold-3-wheel-golf-push-cart.png
The following resources have identical contents, but are served from different URLs. Serve these resources from a consistent URL to save 1 request(s) and 5.9KiB.

https://delmsky2m3lys.cloudfront.net/wp-content/uploads/2016/10/Clicagear-model-3.5.jpg
https://www.bestgolfcartsreviews.com/wp-content/uploads/2016/10/Clicagear-model-3.5.jpg

anyone help me?

**Comment by oschaaf** [comment]
@mejbabiplob It looks like https://www.bestgolfcartsreviews.com is not running mod_pagespeed ?

**Comment by ibraheemsahir** [comment]
Hi Everyone em new to github Need help about page speed errors like

- Serve resources from a consistent URL
- Parallelize downloads across hostnames
- Defer parsing of JavaScript

Kindly send me solutions of all at Ibraheemabbas@gmail.com

**Comment by AizazAyyaz** [comment]
Hi Everyone em new to github Need help about page speed errors like

    

  1.Serve resources from a consistent URL
  2.Minimize request size
  3.Leverage browser caching
  4.Defer parsing of JavaScript

Kindly send me solutions of all at waqasayyaz@gmail.com

**Comment by caknowledge** [comment]
Recently i test my website article https://gst.caknowledge.com/hsn-code-list/  at the gtmetrix.com and i get lowest score for Serve resources from a consistent URL can anyone tell me how can i improve this score...

**Comment by oschaaf** [comment]
@caknowledge To avoid the warning the same content should be served from the same url.
The site you point out has a tracking pixel violating that rule, and also an ad serving script. 

mod_pagespeed is able to automate the js part via the canonicalize js filter: https://www.modpagespeed.com/doc/filter-canonicalize-js
(but it won't be able to help with the pixel)

**Comment by fullenglish** [comment]
Hi, I have the same issue if anyone can help please?

Since enabling page speed I'm getting a low Gtmetrix score for 'Serve resources from a consistent URL' 
The following resources have identical contents, but are served from different URLs. Serve these resources from a consistent URL to save 1 request(s) and 6.7KiB.
http://example.com/skin/frontend/default/images/ajax-loader.gif
http://example/skin/frontend/default/images/ajax-loader.gif.pagespeed.ce.afWLPCz_Xf.gif

The following resources have identical contents, but are served from different URLs. Serve these resources from a consistent URL to save 1 request(s) and 3.5KiB.
http://example.com/media/cms/homepage/Instagram_Icon.png
http://example.com/media/cms/homepage/Instagram_Icon.png.pagespeed.ce.GPkk96k8WF.png

Any ideas please?

**Comment by Rainbowturn** [comment]
1.Serve resources from a consistent URL
2.Minimize request size
3.Leverage browser caching
4.Defer parsing of JavaScript

I need help solve up 4 problems blogger theme, please.
