### ISSUE TITLE
Allow UrlValuedAttribute:image on elements with children

### ISSUE THREAD

**Issue by ypmict** [apache/incubator-pagespeed-mod#1308]
Hi,
I opened a new issue that is related by issue #1297 
That is by using the syntax :

ModPagespeedUrlValuedAttribute li data-thumb image

the image ended up duplicate in the html just like what Mr. @oschaaf  said in the original issue post

Thank you very much

**Comment by jeffkaufman** [comment]
Reproduced.  If you configure a site to be:

```
<li data-thumb="a.jpg">
  <img src="a.jpg">
</li>
```

And you set in your config:

```
ModPagespeedUrlValuedAttribute li data-thumb image
```

Chrome gets:

```
<li data-thumb="a.jpg.pagespeed.ce.O58zxI4ffb.jpg">
<img src="xa.jpg.pagespeed.ic.hq49LFhoZa.webp">
</li>
```

That is, `<li data-thumb=...>` just gets cache-extended, while `<img src=...>` gets fully optimized.  On the other hand, if you have:

```
<li data-thumb="a.jpg"></li>
<img src="a.jpg">
```

Then you get the expected:

```
<li data-thumb="xa.jpg.pagespeed.ic.hq49LFhoZa.webp"></li>
<img src="xa.jpg.pagespeed.ic.hq49LFhoZa.webp">
```

Going from memory, the problem is that any tag that has children isn't considered an acceptable target for image optimization, so it only gets cache-extension here.  I'm not sure why we have this limitation, but it should be fixable.

I've added this to the [Work Prioritization](https://github.com/pagespeed/mod_pagespeed/wiki/Work-Prioritization) sheet.
