### ISSUE TITLE
Test for memcache/redis caches are not independent from each other

### ISSUE THREAD

**Issue by yeputons** [apache/incubator-pagespeed-mod#1351]
It happens because all tests are typically run inside single executable and external servers (such as memcached) are not restarted between tests. So, all data left in cache by a single test is visible to all tests that will be executed right after. Say, if I add these two identical tests, one of them will fail:

```
TEST_F(AprMemCacheTest, Test1) {
  if (!InitMemcachedOrSkip(true)) {
    return;
  }

  CheckNotFound("XXX");
  CheckPut("XXX", "YYY");
}

TEST_F(AprMemCacheTest, Test2) {
  if (!InitMemcachedOrSkip(true)) {
    return;
  }

  CheckNotFound("XXX");
  CheckPut("XXX", "YYY");
}
```

It can be fixed by flushing memcache/redis while setting up test. All other caches, afaik, either fully in-memory or use random temporary directories for each test (like `FileCache`).

**Comment by jmarantz** [comment]
This doesn't seem like a bug that needs desperately to be fixed, just a
limitation to be aware of while writing tests.

We can't fix this at the CacheInterface level because we have no
CacheInterface::FlushEntireCache().  However a memcache-specific or
redis-specific API could be added for testing purposes if this is more
convenient than just being careful with keys &/or cleanup in the test
methods.

Another potential fix is for CacheTestBase to track mutations in CheckPut
and delete them in TearDown.
