### ISSUE TITLE
Lazyload images does not working when the https is enable

### ISSUE THREAD

**Issue by superdoret** [apache/incubator-pagespeed-mod#1363]
When I move my configuration site to HTTP to HTTPS a lot of filters no longer worked. After research a lot I fix almost of them, but ones the main filters still no work. 

Lazyload 
Combine JS
Combine CSS

Any idea ?

**Comment by jmarantz** [comment]
Can you share a URL to your site?  Which are the filters that work now, and
what did you do to fix those?

-Josh

**Comment by superdoret** [comment]
Thanks Joshua for your quick response! The test url of that is https://speed.agrofy.com
I recently fix the lazyload filter, but the combine.js and cobine.css don't working yet.

I fixed the Lazyload for example. 

If you need my configs file please let me know.

**Comment by jmarantz** [comment]
Combine JS looks like it's working to me!

https://speed.agrofy.com/js/mirasvit/core,_underscore.js,qv==2002+core,_backbone.js,qv==2002+code,_searchautocomplete,_form.js,qv==2002+code,_searchautocomplete,_autocomplete.js,qv==2002.pagespeed.jc.3mkNcpi-M0.js

I think Combine CSS doesn't find any candidates because in between your CSS
files you have IE directives and scripts.  We can't move CSS files across
those because it can change functionality.

-Josh

**Comment by superdoret** [comment]
Thanks so much. This is correct. The dev team has an IE directive that I miss to see.
