### ISSUE TITLE
Expiration Date For Woff2

### ISSUE THREAD

**Issue by ghost** [apache/incubator-pagespeed-mod#1404]
Hey Google so i am using the beta downloaded from google and i realized that it dosent set an expiration date for WOFF2 files can u guys please set an expiration date for all the WOFF2 files

**Comment by huibaolin** [comment]
Sorry, we don't optimize WOFF2, so we serve the original.

**Comment by ghost** [comment]
why not??
can u guys add it to the new one
why dont u guys wanna optimize WOFF2 files ??

**Comment by jmarantz** [comment]
Cache-extending woff2 files is a reasonable request.  This would involve renaming the woff2 files as they are referenced from CSS, much like we rename images referenced from CSS.

However, we have not prioritized this optimization because our perception was that you are better off using fonts hosted by font providers, who can set proper expiration dates on them.  Is there any reason why you are not using (say) Google Fonts, and instead hosting them on your own Apache server?

**Comment by ghost** [comment]
i am using fontawesome which requires me to upload the files to my own server and they didnt set an expiration date on it

**Comment by jmarantz** [comment]
It might not be too difficult to set an expiration date in a `<Directory>` block in your Apache configuration file.

**Comment by jeffkaufman** [comment]
Optimizing woff -> woff2 is another thing that it would be great to do at some point.

(It's on https://github.com/pagespeed/mod_pagespeed/wiki/Work-Prioritization but pretty far down)
