### ISSUE TITLE
where to more effective pagespeed load balancer or behind that ?

### ISSUE THREAD

**Issue by dipenpatel235** [apache/incubator-pagespeed-mod#1434]
hello...
i wan to  used nginx with pagespeed.
but i have not idea where can i setup that.
because i have load balancer server and actual site hosting.
both are setup using nginx. 
but confuse where i need to setup nginx with pagespeed module.

So please give me guidance...

Thanks

**Comment by jeffkaufman** [comment]
ngx_pagespeed can run anywhere after you finish generating the html for a page.  So this is a question of where it fits best into your system, not of finding the one place that it will work.

If your level of load is low enough that a single server can manage running ngx_pagespeed then that's probably going to be the simplest setup.  Otherwise, you could install ngx_pagespeed on the site hosting servers, which is also fine.

**Comment by dipenpatel235** [comment]
We have Already using loadbalancer with hosting site.

So we cant remove load balancer..

So i am going to with hosting site server so it is fine ?

**Comment by jeffkaufman** [comment]
That sounds fine!
