### ISSUE TITLE
Javascript Error on my frontend using ModPagespeed

### ISSUE THREAD

**Issue by abieri** [apache/incubator-pagespeed-mod#1547]
On our frontend we get loads of errors of this type. It started few weeks ago a believe, it doesn't seem to affect our experience but we'd like to see if we can avoid these

Uncaught TypeError: Cannot read property 'loadIfVisibleAndMaybeBeacon' of undefined
    at HTMLImageElement.onload (VM78:1)

website : www.jrcigars.com

**Comment by oschaaf** [comment]
One thing I noticed is that the site is running version `1.8.31.4-4009` which is quite old.
I'd really recommend upgrading the module first, before looking into this any further.

**Comment by abieri** [comment]
Thanks @oschaaf it is true that it is a fairly old version. We however have been using that version in production for over 3 years and we started to experience that issue only the past few weeks. Is there anything related to new browser versions or anything else that may cause that issue?

**Comment by oschaaf** [comment]
@abieri sorry late reply, but.. I looked and what I noticed is that with ?PageSpeed=off on the querystring there are still a number of errors like:

```

?PageSpeed=off:1 Uncaught ReferenceError: pagespeed is not defined
    at HTMLImageElement.onload (?PageSpeed=off:1)
onload @ ?PageSpeed=off:1
```

The source has:
```
<script pagespeed_no_defer="">window['pagespeed'] = window['pagespeed'] || {};var pagespeed = window['pagespeed'];pagespeed.switchToHighResAndMaybeBeacon = function(elem) {setTimeout(function(){elem.onload = null;elem.src = elem.getAttribute('pagespeed_high_res_src');if (pagespeed.CriticalImages) {elem.onload = pagespeed.CriticalImages.checkImageForCriticality(elem);}}, 0);};</script>

<div class="animate-container">
<h1 class="text-red text-uppercase sold-text">sold!</h1>
<img pagespeed_lazy_src="https://d2jkh6o5ezxqxc.cloudfront.net/img/rapid-fire/auctions-logo.png" class="sold-image" 
  src="/pagespeed_static/1.JiBnMqyl6S.gif" onload="pagespeed.lazyLoadImages.loadIfVisibleAndMaybeBeacon(this);">
</div>
```

I think the errors can be attributed to something in the website. Maybe some copy pasting of pagespeed optimized html source code into the CMS?

Closing this issue for now.

(I still recommend upgrading!)

**Comment by yugidazai** [comment]
I see that the `pagespeed` field in the site has no "lazyLoadImages" attribute which causes the error 
`Uncaught TypeError: Cannot read property 'loadIfVisibleAndMaybeBeacon' of undefined`

Probably due to : https://developers.google.com/speed/pagespeed/service/LazyloadImages
Should we use `data-pagespeed-no-defer` as the above doc suggests?

**Comment by oschaaf** [comment]
@yugidazai With `PageSpeed=off` the site still had scripts embedded which (should) originate from the module, but instead are embedded into the original sources, perhaps because of some copy/paste work of the optimized html. Perhaps it once worked, but now it has broken, perhaps because of an upgrade of the module or a configuration change, I think.

Note: the doc you point out is for pagespeed service (which was deprecated), see https://modpagespeed.com/doc for the documentation of mod_pagespeed
