### ISSUE TITLE
images are not been rewrite

### ISSUE THREAD

**Issue by nonvwvnon** [apache/incubator-pagespeed-mod#1567]
May i know how do we set the cache-control to public for this site?
https://www.oowdwoo.com/

i would also need tips on how to optimize site that load alot of images on page load.

Thank you.

**Comment by oschaaf** [comment]
Look at https://www.oowdwoo.com/?PageSpeedFilters=+debug, I see a lot of comments like:

```
<!--4xx status code, preventing rewriting of https://www.oowdwoo.com/wdtps/wddw/external/images/wlogo-ss.png-->
```

It looks like mod_pagespeed is not able to fetch your images. It may be worth reading up at https://modpagespeed.com/doc/https_support (specifically "Configuring SSL Certificates").

Alternatively, you can use `MapOriginDomain` or `LoadFromFile` to inform mod_pagespeed how to get to your images in alternative ways.

**Comment by nonvwvnon** [comment]
i went to use maporigindomain

new error
`<!--deadline_exceeded for filter CacheExtender--><!--deadline_exceeded for filter ImageRewrite-->`

**Comment by oschaaf** [comment]
Well I am still seeing the same error. 
Maybe you can check the access logs to verify if and how the requests from mod_pagespeed arrive. (the user-agent header should mention 'mod_pagespeed')?

**Comment by nonvwvnon** [comment]
could this because of cache-control been set to no-cache ?

**Comment by oschaaf** [comment]
The `deadline_exceeded` exceeded messages mean that mod_pagespeed is still working to produce an optimized version for the preceeding resource(s). These messages should go away after a couple of page reloads.

And indeed, mod_pagespeed is not going to optimize uncacheable resources, so that would need fixing. (but I wouldn't have expected the debug comments to mention 404 for uncacheable resources though )
