### ISSUE TITLE
CSS minifier breaks unicode-range values

### ISSUE THREAD

**Issue by peterbleickardt** [apache/incubator-pagespeed-mod#1572]
What steps will reproduce the problem?
1. Activate CSS minification in mod_pagespeed
2. Include a `unicode-range` CSS declaration in a stylesheet: `unicode-range: U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116`

What is the expected output?
`unicode-range:U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116`

What do you see instead?
The CSS minification output breaks the value, placing a space between the 'U' and '+':

`unicode-range:U +0400-045F , U +0490-0491 , U +04B0-04B1 , U +2116`

This prevents the browser from seeing the proper value, therefore always downloading the font even if the intended range of characters is not used.

What version of the product are you using?
X-Mod-Pagespeed: 1.11.33.4-0

Which OS? Which version of Apache? Which MPM?
CentOS, Apache/2.2.27 (prefork)

**Comment by jmarantz** [comment]
Thanks for the report.   For quick workaround, I suggest using ModPagespeedDisallow to avoid processing the CSS file with the unicode characters.  Hopefully this (a) doesn't affect all of them and (b) maybe you could split it just the rules that have this.

I'll check into what the status of this is.  A few things are fixed in 1.12 (that's now stable) however this one doesn't ring a bell.
