### ISSUE TITLE
modpagespeed is not working in my website

### ISSUE THREAD

**Issue by sankarkodali** [apache/incubator-pagespeed-mod#1576]
Modpagespeed is enabled in our server. But it is not working in mywebsite

Kindly check the below htacces file and help me to solve this issue

My Website is ***

<IfModule mod_expires.c>
ExpiresActive On
ExpiresByType image/jpg "access 1 year"
ExpiresByType image/jpeg "access 1 year"
ExpiresByType image/gif "access 1 year"
ExpiresByType image/png "access 1 year"
ExpiresByType text/css "access 1 month"
ExpiresByType text/html "access 1 month"
ExpiresByType application/pdf "access 1 month"
ExpiresByType text/x-javascript "access 1 month"
ExpiresByType application/x-shockwave-flash "access 1 month"
ExpiresByType image/x-icon "access 1 year"
ExpiresDefault "access 1 month"
</IfModule>

<IfModule pagespeed_module>
    AddOutputFilterByType MOD_PAGESPEED_OUTPUT_FILTER text/html
    ModPagespeed on
    ModPagespeedLowercaseHtmlNames on
 
    ModPagespeedEnableFilters extend_cache
    ModPagespeedEnableFilters insert_dns_prefetch
 
#
# Text / HTML
#
 
    ModPagespeedEnableFilters collapse_whitespace
    ModPagespeedEnableFilters convert_meta_tags
    ModPagespeedEnableFilters remove_comments
    ModPagespeedEnableFilters collapse_whitespace
    ModPagespeedEnableFilters elide_attributes
    ModPagespeedEnableFilters trim_urls
    ModPagespeedEnableFilters pedantic
 
#
# JavaScript
#
 
    ModPagespeedEnableFilters combine_javascript
    ModPagespeedEnableFilters canonicalize_javascript_libraries
    ModPagespeedEnableFilters rewrite_javascript
    ModPagespeedEnableFilters defer_javascript
    ModPagespeedEnableFilters inline_javascript
 
#
# CSS
#
 
    ModPagespeedEnableFilters rewrite_css
    ModPagespeedEnableFilters combine_css
    ModPagespeedEnableFilters move_css_to_head
    ModPagespeedEnableFilters inline_css
    ModPagespeedEnableFilters inline_import_to_link
    #ModPagespeedEnableFilters move_css_above_scripts
 
#
# Images
#
 
    ModPagespeedEnableFilters inline_preview_images
    ModPagespeedEnableFilters insert_img_dimensions
    ModPagespeedEnableFilters rewrite_images
    ModPagespeedEnableFilters recompress_images
    #ModPagespeedEnableFilters convert_jpeg_to_progressive
    ModPagespeedEnableFilters resize_mobile_images
    #ModPagespeedEnableFilters sprite_images
    #ModPagespeedEnableFilters lazyload_images

    #ModPagespeedEnableFilters convert_png_to_jpeg,convert_jpeg_to_webp
    ModPagespeedEnableFilters collapse_whitespace,remove_comments
 
    ModPagespeedEnableFilters local_storage_cache
 
</IfModule>

**Comment by oschaaf** [comment]
I can't access the site because some software running on my machine marked it as containing a security threat. (don't know what triggers it). I editted your comment to remove the domain.

Looking from another machine with curl:
- the https cert is not valid for the domain
- assets are not hosted from the same domain as https.

You can add `?PageSpeedFilters=+debug` to the querystring to get the module to write debug comments about fetch failures..
- You probably need to tweak https support to allow for fetching from servers with invalid certificates:
https://modpagespeed.com/doc/https_support
- You may have to authorize the module to fetch and optimize from the domains that host the images/css/jss: https://modpagespeed.com/doc/domains

Closing this, but feel free to re-open if there is an issue with the module.
