### ISSUE TITLE
Failed to make directory  Permission denied

### ISSUE THREAD

**Issue by Nirjonadda** [apache/incubator-pagespeed-mod#1615]
Hello,

Everyday I get my site down for 3/5 minutes from following error message. Please let me know that how I can get fixing this error?

````
CentOS Linux release 7.3
cPanel v66.0.12 EA4
````

````
[Tue Aug 15 19:06:43.963322 2017] [pagespeed:error] [pid 10383:tid 139862369806080] [mod_pagespeed 1.11.33.4-0 @10383] Failed to make directory /var/mod_pagespeed/cache/rname: Permission denied
````

**Comment by jmarantz** [comment]
Depending on your distro & apache install process, the username associated with your apache child processes may be something like www-user or www-data.   Make sure that user has full write access to /var/mod_pagespeed_cache, which (I assume) is something you hand-configured in pagespeeed.conf because that doesn't look like our default, which I believe is /var/cache/mod_pagespeed.

In either case, www-data or www-user needs to have write access to the cache directory.
