### ISSUE TITLE
How to turn it OFF into an Apache Virtualhost Directory?

### ISSUE THREAD

**Issue by 7starsone** [apache/incubator-pagespeed-mod#1693]
Hello,
i'm on an Apache `Directory`

I tried

```
<IfModule pagespeed_module>
ModPagespeed off //this one alone, the below alone, even the 2 together
ModPagespeed unplugged
</IfModule>
```

nothing to do.

- If I turn it **off** on `pagespeed.conf` I can't **enable** it into the Directory
- If I turn it **on** on `pagespeed.conf` I can't **disable** it into the Directory

am I missing something... ?

Thank you

**Comment by 7starsone** [comment]
I had to do

```
<IfModule pagespeed_module>
ModPagespeed unplugged
</IfModule>
```


**outside** the Directory
but this way it disables mod_pagespeed for the entire Virtualhost.

At the moment, I can't understand if possible to disable mod_pagespeed per `Directory`

Can you better explain this matter, please?
Thanks

**Comment by jmarantz** [comment]
Can you try `standby`?  Here's a brief description on the names:

- `ModPagespeed standby`: disables the module in a way that it can be turned on again by query-param or at a lower level
- `ModPagespeed unplugged`: completely disables the module for the server, with no way to turn it on by query-param or in a subdirectory
- `ModPagespeed on`: enables the module in the directory & below, as long as the state is not `unplugged`

Brief history: we originally had "on" and "off".  Later we added `unplugged` because we wanted site owners a way to hit a big kill switch in case something went wrong. `off` meant `standby` in MPS, but `off` meant `unplugged` in ngx_pagespeed (NPS), which was an oversight when we built NPS.

To make this consistent (since the modules share doc) we decided to deprecate `off` and ask users to explicitly say `unplugged` or `standby` which work the same way in both server modules.

**Comment by 7starsone** [comment]
I'm on **1.12.34**
so, I can't even use `standby` and it returns error on the syntax

for now, I need to
`ModPagespeedDisallow "*mydomain.com/mydir/*"` inside **pagespeed.conf**
anyway, thank you

**Comment by jmarantz** [comment]
On MPS 1.12, "off" should work as you described, but Disallow is fine as well.

**Comment by 7starsone** [comment]
I tried "off" but it didn't work in the `Directory`, probably I got confused by my cookieless domain 
eg. `static.domain` because in the page source I still saw many pagespeed lines...

so, in order not to write other rules for the static domain, I used disallow...
ok, thanks for now
