### ISSUE TITLE
Ressources not written because restrictive cache almost 100% and cache misses over 70%

### ISSUE THREAD

**Issue by ajconejo** [apache/incubator-pagespeed-mod#2034]
Hi

I have installed pagespeed 1.13.35.2-0 with the following configuration and console shows that ressorces are not written because of restrictive cache control and have a high rate of cache misses.

Message history does not show any special message about cache misses.

apache logs does not show any special message either.

I have some warns like
RateController: drop deferred fetch
WARNING:serf_url_async_fetcher.cc(1222)

What  could be the cause?  Is there a way to see what content is being missed? I tried to enable filter debug but apache error/access logs shows nothing

Thanks

===============
I´m on Ubuntu 18.04

pagespeed info
===============
Version: 14: on

Filters
gp	Convert Gif to Png
jp	Convert Jpeg to Progressive
jw	Convert Jpeg To Webp
pj	Convert Png to Jpeg
db	Debug
di	Delay Images
hw	Flushes html
ji	Inline Javascript
io	In-place optimize for browser
js	Jpeg Subsampling
co	Outline Css
rj	Recompress Jpeg
rp	Recompress Png
rw	Recompress Webp
cf	Rewrite Css
jm	Rewrite External Javascript
jj	Rewrite Inline Javascript
cp	Strip Image Color Profiles
md	Strip Image Meta Data

Options
  DefaultSharedMemoryCacheKB (dsmc)             50000
  EnableRewriting (e)                           1
  FetchWithGzip (afg)                           True
  FileCacheCleanIntervalMs (afcci)              3600000
  FileCacheInodeLimit (afcl)                    500000
  FileCachePath (afcp)                          /var/cache/mod_pagespeed/
  FileCacheSizeKb (afc)                         409600
  HonorCsp (hcsp)                               True
  ImageMaxRewritesAtOnce (im)                   12
  InPlaceResourceOptimization (ipro)            True
  LoadFromFileCacheTtlMs (lfct)                 60000000
  LogDir (ald)                                  /var/log/pagespeed
  LRUCacheByteLimit (alcb)                      16384
  LRUCacheKbPerProcess (alcp)                   1024
  MaxCacheableContentLength (rcl)               16777216
  MemcachedServers (ams)                        localhost:11211
  PreserveUrlRelativity (pur)                   True
  RespectVary (rv)                              True
  RewriteLevel (l)                              Optimize For Bandwidth
  ShmMetadataCacheCheckpointIntervalSec (smci)  300
  SslCertDirectory (assld)                      /etc/ssl/certs
  StatisticsLogging (asle)                      True

Domain Lawyer
  http://*.celacp.org/ Auth
  http://*.googletagmanager.com/ Auth
  http://*.ssl-images-amazon.com/ Auth
  http://45.79.198.124/ Auth
  https://*.celacp.org/ Auth
  https://*.googletagmanager.com/ Auth
  https://*.ssl-images-amazon.com/ Auth
  https://biblioteca-admin.celacp.org/ Auth
  https://biblioteca.celacp.org/ Auth
  https://upload.wikimedia.org/ Auth

Invalidation Timestamp: (none)

The headers of my main page are
======================
Server Apache
X-Frame-Options SAMEORIGIN SAMEORIGIN
Content-Security.Policy default-src https: 'upgrade-insecure-requests' 'unsafe-eval' 'unsafe-inline'; object-src 'none'
X-Content-Security.Policy default-src https: 'upgrade-insecure-requests' 'unsafe-eval' 'unsafe-inline'; object-src 'none'
Strict-Transport-Security max-age=31536000; includeSubDomains max-age=3153600
Cache-Control max-age=0, no-cache
Pragma no-cache
Content-Script-Type text/javascript
Content-Style-Type text/css
X-Mod-Pagespeed 1.13.35.2-0
Vary Accept-Encoding,User-Agent
Set-Cookie CGISESSID=23302c50afaebc5c8b9f777556a72297; path=/; HttpOnly;HttpOnly;Secure
X-Content-Type-Options nosniff
X-XSS-Protection 1; mode=block
Content-Length 219221
 Content-Type text/html; charset=UTF-8

**Comment by Lofesa** [comment]
First, you can´t auth any domain that don´t run pagespeed module, so many of the domains you have auth are bad,
Example, I´m sure wikimedia is not running pagespeed module. What happens when you auth these domain? Pagespeed module rewrites the resource (some like `https://upload.wikimedia.org/some-path/some-file.jpg.ic.pagespeed.SOMEHASH.webp`) but these rewrited resource don´t exists so you get a 404 in return.
More.  You have `http://.celacp.org/ Auth` but latter you have `https://biblioteca-admin.celacp.org/ Auth`, this make me thinking your own domain is celacp.org and are served by https, but you have http.
Try to use `http*://*.celacp.org` in this way you have auth both versions http and https, and all subdomains from celacp.org, don´t need separate directives for biblioteca and bilioteca-admin subdomains.
You have set `SslCertDirectory (assld) /etc/ssl/certs` but don´t have enabled the https fecht `ModPagespeedFetchHttps enable`, You must reviewd the docs about direct fecht https here: https://www.modpagespeed.com/doc/https_support#https_fetch .
You have set `LoadFromFileCacheTtlMs (lfct) 60000000`, but don use LoadFromFile at all. This directive is an alternate way to load resources from disk other than load it fechting by a http request.
If you will to use LoadFrom File you must read these doc:  https://www.modpagespeed.com/doc/https_support#load_from_file
and then enable selective file load https://www.modpagespeed.com/doc/domains#ModPagespeedLoadFromFile.

Any way... the message you have about restrictive cache headers is cause the resources pagespeed will rewrite (and optimize) have a cache-control header not public cacheable. So must have a `cache-control: max-age=some value, public`. Your resources don´t have any cache-control header, and the main request have` Cache-Control: post-check=0, pre-check=0`, I think these header make the request not public cacheable.

When su use debug filter, the debug messages are NOT logged in any log file, nor apache nor pagespeed. The debug messages are in the html code of the page, to read it you need to view the page code

**Comment by Lofesa** [comment]
Well... the 1st step to debug is putting all things in the rigth side. 
png images still not full optimized becasue it have transparent pixels or are sensitive to compression noise, but are optimized by IPRO. You can see it because the eTag header: `Etag: W/"PSA-aj-nbqpw_qrXQ-br"` , these etag header is set by IPRO, you can se that Conten-legth and X-Content-legth mismacht, these are the result of partial optimization, IPRO don´t rewrite the url.

About the js and css files, can you try to set:
`ModPagespeedModifyCachingHeaders  on`

And find from where comes this header (see the image), there is a no-cache header
![Captura](https://user-images.githubusercontent.com/22342793/91297729-1668ba80-e79f-11ea-921f-44fab27d4c9e.jpg)

**Comment by ajconejo** [comment]
Hi,

Have restarted mod_pagespeed config from scratch and found that the header issue and cache misses comes from the LoadFromFile... might be a bug?

I didn´t changed anything on the cache-control headers on my pages and when replacing:

ModPagespeedLoadFromFile "https://biblioteca.celacp.org/opac-tmpl/bootstrap/images/" 
"/usr/share/koha/opac/htdocs/opac-tmpl/bootstrap/images/"
ModPagespeedLoadFromFile "https://biblioteca.celacp.org/opac-tmpl/bootstrap/itemtypeimg/" "/usr/share/koha/opac/htdocs/opac-tmpl/bootstrap/itemtypeimg/"

With

ModPagespeedLoadFromFile "https://biblioteca.celacp.org/opac-tmpl/bootstrap/" "/usr/share/koha/opac/htdocs/opac-tmpl/bootstrap/"

I start getting the cache-control errors and caches mises

In both cases I have:

ModPagespeedInPlaceResourceOptimization on
ModPagespeedLoadFromFileRuleMatch disallow .*
ModPagespeedLoadFromFileRuleMatch allow .(ico|pdf|swf|eot|woff|ttf|otf|css|js|jpeg|jpg|png|gif|svg|svgz|mpg|mpeg|mp3|m4a|m4v|mp4|ogg|wmv|mov|mng|3gpp|3gp|webp|webm|flv|avi|asx|asf)$

This is my current full config:

Version: 14: on

Filters
ah	Add Head
ij	Canonicalize Javascript library URLs
cc	Combine Css
jc	Combine Javascript
gp	Convert Gif to Png
jp	Convert Jpeg to Progressive
jw	Convert Jpeg To Webp
mc	Convert Meta Tags
pj	Convert Png to Jpeg
ws	When converting images to WebP, prefer lossless conversions
db	Debug
di	Delay Images
ec	Cache Extend Css
ei	Cache Extend Images
es	Cache Extend Scripts
fc	Fallback Rewrite Css 
if	Flatten CSS Imports
hw	Flushes html
ci	Inline Css
ii	Inline Images
il	Inline @import to Link
ji	Inline Javascript
io	In-place optimize for browser
js	Jpeg Subsampling
rj	Recompress Jpeg
rp	Recompress Png
rw	Recompress Webp
ri	Resize Images
cf	Rewrite Css
jm	Rewrite External Javascript
jj	Rewrite Inline Javascript
cu	Rewrite Style Attributes With Url
cp	Strip Image Color Profiles
md	Strip Image Meta Data

Options
  CacheFlushPollIntervalSec (acfpi)             1296000
  EnableCachePurge (euci)                       True
  EnableRewriting (e)                           1
  FetchWithGzip (afg)                           True
  FileCacheCleanIntervalMs (afcci)              36000000
  FileCacheInodeLimit (afcl)                    500000
  FileCachePath (afcp)                          /var/cache/mod_pagespeed/
  FileCacheSizeKb (afc)                         409600
  HttpCacheCompressionLevel (hccl)              9
  InPlaceResourceOptimization (ipro)            True
  LoadFromFileCacheTtlMs (lfct)                 600000
  LogDir (ald)                                  /var/log/pagespeed
  LRUCacheByteLimit (alcb)                      16384
  LRUCacheKbPerProcess (alcp)                   1024
  MaxCacheableContentLength (rcl)               20000000
  MaxCombinedCssBytes (xcc)                     -1
  MaxCombinedJsBytes (xcj)                      -1
  MemcachedServers (ams)                        localhost:11211
  PrivateNotVaryForIE (pnvie)                   True
  PurgeMethod (pm)                              PURGE
  RateLimitBackgroundFetches (rlbf)             False
  RewriteRandomDropPercentage (rrdp)            -1
  ShmMetadataCacheCheckpointIntervalSec (smci)  300
  SslCertDirectory (assld)                      /etc/ssl/certs
  StatisticsLogging (asle)                      True

Domain Lawyer
  http*://*.celacp.org/ Auth
  http*://*.googletagmanager.com/ Auth
  http*://*.ssl-images-amazon.com/ Auth
  http*://45.79.198.124/ Auth

Invalidation Timestamp: (none)

**Comment by Lofesa** [comment]
But now you have it working...
Some js files are not rewrited because they are loaded by other js file.
Example `https://biblioteca.celacp.org/opac-tmpl/bootstrap/js/script_19.1108000.js` is loaded by `https://biblioteca.celacp.org/opac-tmpl/bootstrap/lib/modernizr.min_19.1108000.js.pagespeed.jm.Yq80J6k3xh.js` but get some type of optimization as far as their `Etag: W/"PSA-aj-6kR3KjB27V"`. The PSA denotes the IPRO work.
Same with the css file `https://biblioteca.celacp.org/plugin/Koha/Plugin/Com/ByWaterSolutions/CoverFlow/bower_components/jquery-flipster/dist/jquery.flipster.min.css`

Whit some images, like wikipedia-16.png, are in a `<picture> srcset` element, pagespeed don´t rewrite these until a next version, when the PR #1929 get merged.
With images loaded by a .pl script, some type of optimization is done, as far as I can see the `W/"PSA-aj-bpsLvimpe6-br"`  and `Content-Length: 4951`  `X-Original-Content-Length: 49569` for `https://biblioteca.celacp.org/cgi-bin/koha/opac-image.pl?biblionumber=238112&thumbnail=1`. Here the PSA in the Etag header is set by IPRO.

**Comment by ajconejo** [comment]
I´ve tuned the load from file paths and that seems to fix the issue.
Thanks to all who help
