### ISSUE TITLE
Arial #000 instead of Arial black

### ISSUE THREAD

**Issue by omgMath** [apache/incubator-pagespeed-mod#2049]
We have a website based on `next.js` running. We got reports of the wrong font appearing. I was able to reproduce the issue on my phone, but strangely not on my desktop.

In the failing case the problem was obvious:
When I checked the styles in the debugger, i saw the following: `font-family: Graph Condensed,Impact,Arial #000,Arial,sans-serif`.

Then again, in my Firefox everything looked fine: `font-family: Graph Condensed, Impact, "Arial black", Arial, sans-serif;`, while the initial reporter had the same problem in Firefox as well.

I also checked the `css` compiled/built from `scss` on the server. Everything looked fine, no "Arial #000" in there.

Since the generated `css` looks good, it happens cross-browser and inconsistently within the same type of browser: We are also using `incubator-pagespeed-mod 1.11.33.5-0` in case that helps investigating - could this be causing that issue?

Thank you for your support!

PS:  I realize our version is quite outdated, I will try to get our host to update to the newest version.
PPS: If it is clear to one of you that something else is more likely to cause this, I will try to open an issue there.

**Comment by Lofesa** [comment]
Have you tried to disable pagespeed and see if the issue still here?
Don´t need to restart the web server, it can be acomplised in a request basis, try:

`https://mydomain.com/?PageSpeed=off`

or even disable css rewrite in a request

`https://mydomain.com/?PageSpeedFilters=+debug,-rewrite_css`

the +debug put debug messages in the html code, so you can inspect these messages viewing the code of the page.

**Comment by omgMath** [comment]
In the meantime we've removed "Arial black" from our fonts.
I will try to reproduce the issue on stage and let you know whether we succeed - and what happens when adding the query parameters you mentioned.

**Comment by Lofesa** [comment]
Hi again
With ?PageSpeed=off Pagespeed is disabled for this request so you can test if the issue is here witout pagespeed. If the issue is here w/o pagespeed then you need to look other things.
Whit ?PageSpeedFilters=+debug the module put debug messages as html comments. So looking in the html code of the page you have some debug info.
Adding a - (minus sign) you can disable a filter, adding + (plus sign) you can enable a filter.
So with ?PageSpeedFilters =+debug,-rewrite_css you have debug messages in the html code and the rewrite_css filter is disabled only for this concrete request.
These query parameters are case sensitive, you can´t use ?pagespeedfilters=+DEBUG.
In this way you can enable or disable filters w/o changing the config files and w/o restarting the web server.
In PageSpeedFlters you can add more than 2 filters with , (comma) delimiter.
You can see it at https://www.modpagespeed.com/doc/experiment#ModPagespeed

**Comment by omgMath** [comment]
Tried to reproduce it for over an hour now. No luck so far.
Don't really know where it came from or how to reproduce that bug.

Feel free to close this bug in case you need a proper reproduction. I probably won't be able to deliver one...

**Comment by Lofesa** [comment]
Have you tried on a stage server? Have you re-add the font in production?

**Comment by omgMath** [comment]
I now re-added the font to the Prod instance, and was able to reproduce the issue again.

It still occurred with `?PageSpeed=off`, so it does not seem to be related to this library. (Unless this parameter is not respected for some reason?)

Thanks for your help debugging.

**Comment by Lofesa** [comment]
Hi
When you use `?PageSpeed=off` you can check that no file is rewrited, no x-page-speed header is set.. maybe IPRO still working, but if you have tried it on a stage server and not have the issue, likely is not related to pagespeed but other thing in the prod server.
You say the issue is in mobile device so have you tried other browser in mobile or the same brownser in desktop?
Have other css optimizer in the prod server?
Sound like some thing is changing color names to color hex, but AFAIK pagespeed only do a minifycation with the css.

**Comment by omgMath** [comment]
Ok, with `?PageSpeed=off` I didn't get a header entry for `x-mod-pagespeed` (I think that's the one you meant?).

The thing is really strange. So far the reporter or I were able to reproduce the issue on

- Firefox, Chrome, Brave (MacOS)
- Brave (iOS, Android)


but not on

- Firefox, Brave (Linux Mint)
- Chrome (Android)

Here is what I see in the debugger in the working
![working](https://user-images.githubusercontent.com/24620670/98716041-37e34680-238b-11eb-9933-04756999f295.jpeg)

and the failing case
![failing](https://user-images.githubusercontent.com/24620670/98716040-374ab000-238b-11eb-801b-97013f0ed664.jpg)

You can see that it is the same css file loaded, but in one browser it's correct, in the other one it is not. Which is really weird, because those should be static files.
We have `gzipping` enabled on Apache level, but I don't think this is the culprit?

**Comment by Lofesa** [comment]
Have you enablled the in_place_optimize_for_browser filter?
I found this [#1489](https://github.com/apache/incubator-pagespeed-ngx/issues/1489), maybe unrelated.
Sounds like some related with user agent.
If so you can try https://mysite.com/?PageSpeedFilters=-in_place_optimize_for_browser
At this point you can make some experiment:

1.- Whats happens if you disallow this file? (ModPagespeedDisallow wildcard_spec)
2.-Whats happens if you put an uncacheable http header for this file? (cache-control: private)
3.- What if put a @font-face? (in the images you posted I can´t see **@font-face**{ font-family:.....} so maybe rewrite_css will take this as a "normal" css and in these snippet "black" is a color, not the name of any thing)

**Comment by omgMath** [comment]
With `?PageSpeedFilters=-in_place_optimize_for_browser` the problem still remains.

Not sure if I managed to do your suggested experiments correctly, but

1. No change - still the wrong font used (added `ModPagespeedDisallow "*/324db4ee0095426f1709.css"` to the `.htaccess`)
1. No change - still the wrong font (added   -H 'cache-control: private' to the curl request)
1. The font-face is defined at some other part:
```CSS
@font-face{
  font-family:Graph Condensed;
  src:url(/static/fonts/graph/graph/condensed-bold/graph-condensed-bold-web.ttf)
}
```

Hope I did everything correctly, otherwise please let me know.

**Comment by Lofesa** [comment]
Well... strart to think is not pagespeed related.
With 1 and 2 pagespeed must bypass the file, with 1 in pagespeed logs you must see some like "don´t rewrite because is disallowed" and with 2 some like "don´t rewrite because bad cache headers", and no pagespeed filters must be applied, in 1 to these file, in 2 to the whole page.
The last try is to put pagespeed totally off with `ModPagespeed unplugged` , not `ModPagespeed off` because this is a stanby mode, some things still working, like IPRO.
I don´t know next.js, so can´t help with this, sorry for that.

**Comment by omgMath** [comment]
Thank you for your help and ideas. I agree - this is most likely not related to Pagespeed.
