### ISSUE TITLE
support srcset or picture attribute

### ISSUE THREAD

**Issue by GoogleCodeExporter** [apache/incubator-pagespeed-mod#791]
```
See http://www.w3.org/html/wg/drafts/srcset/w3c-srcset/

I think this could be done with a default configuration to 
ModPagespeedUrlValuedAttribute 

```

Original issue reported on code.google.com by `jmara...@google.com` on 30 Sep 2013 at 1:30

**Comment by sligocki** [comment]
We've added a new `responsive_images` filter in trunk which will be available in release 1.10. It converts an image like `<img src="foo.png" width="100" height="100">` to: `<img src="100x100xfoo.png.pagespeed.ic.HASH1.png" width="100" height="100" srcset="150x150xfoo.png.pagespeed.ic.HASH2.png 1.5x,200x200xfoo.png.pagespeed.ic.HASH3.png 2x>` as long as `foo.png` is at least 200x200 natively.

So you can get responsive images by setting the src equal to a 2x version of the image and then turning on `responsive_images`.

**Comment by tomasdev** [comment]
@sligocki is there a way to put the opposite behavior?

Something like given `foo.png` size `600x600` be able to put an `<img>` tag (which could have `width: 20%`) such as that it converts into `<img src="100x100xfoo.png.pagespeed.ic.HASH1.png" width="100" height="100" srcset="120x120xfoo.png.pagespeed.ic.HASH2.png 120w, 300x300xfoo.png.pagespeed.ic.HASH3.png 300w" sizes="(max-width: 600px) 120px, 50vw">` or similar?

Otherwise it seems PageSpeed will always complain about images that are relative to width, given a test could be on 320px wide (mobile) and 1024px wide (desktop) and for the given 20% that is a 218% variance. 

Or even simpler, an image that is used at 100% of the width ("full-bleed") would have this problem as well, as mobile needs a 320 or 375 wide image, while a MacBookPro could need 1920 or even 2880...

**Comment by tomasdev** [comment]
From my understanding, in last beta (1.12) technically an approach could be to have the back-end generate all different sizes, and the markup have the srcset already for when ModPageSpeed optimizes the resources...

Not ideal, but better than nothing.

**Comment by sligocki** [comment]
@tomasdev, I'm afraid I haven't worked on this project in about 2 years. I'd suggest you ask on the discussion group.
